version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/quotesapp
    networks:
      - quotesgenerator
  php:
    image: 'php:fpm'
    volumes:
      - .:/quotesapp
    networks:
      - quotesgenerator
networks:
  quotesgenerator:
    driver: bridge